#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_yubikey="0.0.1"
  jq -n --arg yubikey "$ver_yubikey" '{yubikey: $yubikey}'
}

version "$@"
